server:
  address: 0.0.0.0
activemq:
  brokerUrl: ${ACTIVEMQ_BROKER_URL:vm://localhost:61616}
queue:
  name: ${QUEUE_NAME:mainQueue}
worker:
  name: ${HOSTNAME:worker1}
  enabled: ${WORKER_ENABLED:true}
store:
  enabled: ${STORE_ENABLED:true}
dbConnection:
  ipAddress: ${DB_IP_ADDRESS:104.197.15.242}
  database: ${DB_NAME:postgres}
  port: ${DB_PORT:5432}
  user: ${DB_USER:postgres}
  password: ${DB_PASSWORD:password}
