apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
  labels:
    app: queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
        - name: web
          image: webcenter/activemq:5.14.3
          imagePullPolicy: Always
          ports:
            - containerPort: 61616
          resources:
            limits:
              memory: 512Mi

