apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  ports:
    - nodePort: 32000
      port: 80
      targetPort: 8888
  selector:
    app: frontend
  type: LoadBalancer
